image: devwithlando/gitpod:1

tasks:
  - name: Start Drupal
    command: |
      lando start
      gp preview $(gp url $(lando info --format=json | jq -r ".[0].urls[1]" | sed -e 's#http://localhost:\(\)#\1#'))

ports:
  - port: 3306
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 8443
    onOpen: ignore
  - port: 9003
    onOpen: ignore
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: ignore


